name: ImgBot
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  img_optimization:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Optimize images
        uses: imgbot-io/ImgBot-action@v1.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
